image:
  repository: mysql
  tag: "8.0"

service:
  name: mysql-service
  port: 3306

storage:
  size: 5Gi
  storageClass: host-storage
  hostPath: /mnt/mysql-data

nodeSelector:
  kubernetes.io/hostname: mycluster-worker

config:
  MYSQL_DATABASE: notesdb

secret:
  MYSQL_ROOT_PASSWORD: root
  MYSQL_USER: notes_user
  MYSQL_PASSWORD: notes_password
