labels:
  app: mysql

replicaCount: 1

image:
  repository: mysql
  tag: "8.0"
  pullPolicy: IfNotPresent

service:
  name: mysql-service
  port: 3306

storage:
  size: 5Gi
  storageClass: gp3   # âœ… EKS-compatible

config:
  MYSQL_DATABASE: notesdb

secret:
  MYSQL_ROOT_PASSWORD: root
  MYSQL_USER: notes_user
  MYSQL_PASSWORD: notes_password
