labels:
  app: mysql

replicaCount: 1

image:
  repository: ""
  tag: "latest"
  pullPolicy: IfNotPresent

service:
  name: mysql-service
  port: 3306

storage:
  size: ""
  storageClass: ""

config: {}

secret: {}
