apiVersion: v1
kind: PersistentVolume
metadata:
  name: mysql-pv
spec:
  capacity:
    storage: {{ .Values.storage.size }}
  accessModes:
    - ReadWriteOnce
  storageClassName: {{ .Values.storage.storageClass }}
  persistentVolumeReclaimPolicy: Retain
  hostPath:
    path: {{ .Values.storage.hostPath }}
    type: DirectoryOrCreate
